apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  # Explicit 'readOnly: false' applied to 'mountPath' causes perpetual out-out-sync
  # https://github.com/argoproj/argo-cd/issues/19038
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: cluster-wide-apps
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.16.1
    helm:
      releaseName: cilium
      values: |
        kubeProxyReplacement: true
        k8sServiceHost: 192.168.11.110 # modify it if necessary
        k8sServicePort: 6443
        loadBalancer:
          algorithm: maglev
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
          metrics:
            enabled:
            - dns:query;ignoreAAAA
            - drop
            - tcp
            - flow
            - icmp
            - http
            - port-distribution
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
