defaultSettings:
  # # When this setting is disabled, Longhorn creates a default disk on each node that is added to the cluster.
  createDefaultDiskLabeledNodes: false
  defaultDataPath: /mnt/longhorn-xfs/
  replicaSoftAntiAffinity: true
  storageOverProvisioningPercentage: 1000
  storageMinimalAvailablePercentage: 5
  upgradeChecker: true
  defaultReplicaCount: 3
  defaultDataLocality: disabled
  priorityClass: high-priority
  autoSalvage: true
  disableSchedulingOnCordonedNode: false
  replicaZoneSoftAntiAffinity: true
  replicaDiskSoftAntiAffinity: true
  # ref: https://longhorn.github.io/longhorn-tests/manual/pre-release/node/improve-node-failure-handling/
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  guaranteedInstanceManagerCpu: 20
  orphanAutoDeletion: true
