apiVersion: v1
kind: Service
metadata:
  name: minio-lb
  namespace: tenant-1
spec:
  type: NodePort
  ports:
    - port: 9443
      targetPort: 9443
      nodePort: 30003
      protocol: TCP
  selector:
    v1.min.io/tenant: minio-tenant-1
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  rootUser: bWluaW8=
  rootPassword: bWluaW8xMjM=
  lokiPassword: bG9raVBhc3N3b3Jk
  tempoPassword: dGVtcG9QYXNzd29yZA==
